### PR TITLE
Fix ksm

### PR DESCRIPTION
**Pull request by roedie**
The endif is still on the wrong line. If you do not manage the ksm_service file saltstack will fail:

```
      ID: ksm_service
Function: service.running
    Name: ksm
  Result: False
 Comment: The named service ksm is not available
 Started: 14:04:43.612249
Duration: 57.123 ms
 Changes:   
```

### CODE REVIEW

**Comment by roedie** [comment]
Aw drats... this is not what I meant to do. I only wanted to push the last commit

**Comment by arnisoph** [comment]
@roedie It's now possible to disable ksm service management. Simply set the following pillar:

```
libvirt:
  lookup:
    kvm:
      ksm:
        service:
          manage: false
```

**Comment by arnisoph** [comment]
FYI: the ksm init script should be already available on RHEL and some other systems

**Comment by roedie** [comment]
@bechtold If I put the above in my pillar I still get the error:

ID: ksm_servicescript
Function: file.managed
Name: /etc/init.d/ksm
Result: False
Comment: Source file salt://libvirt/files/ksm/init_ksm not found
Started: 08:48:31.019771
Duration: 3.261 ms
Changes:   

I do believe this is because the {% endif %} is on the wrong line, which is fixed by 21401fd

**Comment by arnisoph** [comment]
well, to disable script management too you need to set a second pillar:

```
libvirt:
  lookup:
    kvm:
      ksm:
        service_script:
          manage: false
        service:
          manage: false
```

**Comment by roedie** [comment]
&@#%$&... I must have been blind or something. Sorry about that.

**Comment by arnisoph** [comment]
No worries, glad to see users of my formulas.

**Pull request closed without merging**
